# Generated by Django 3.0 on 2020-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200812_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='phonenumber',
            field=models.CharField(max_length=200),
        ),
    ]
