# Generated by Django 3.0 on 2020-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200812_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
